/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.smart.inventory.management;

import com.formdev.flatlaf.FlatLightLaf;
import com.mycompany.smart.inventory.management.UI.AppColors;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.UIManager;
import com.mycompany.smart.inventory.management.model.User;
import com.mycompany.smart.inventory.management.service.AuthService;
import javax.swing.JOptionPane;

/**
 *
 * @author danar
 */
public class LoginFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());
    private AuthService authService = new AuthService();

    private void setupLoginUI() {
        setTitle("Login - Smart Inventory Management");
        setSize(900, 550);
        setLocationRelativeTo(null);
        setResizable(false);

        mainPanel.setBackground(new Color(243, 244, 246));
        leftPanel.setBackground(new Color(243, 244, 246));

        loginCardPanel.setBackground(Color.WHITE);
        loginCardPanel.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(229, 231, 235)),
                BorderFactory.createEmptyBorder(30, 35, 30, 35)
        ));

        lblBrandTitle.setFont(new Font("Segoe UI", Font.BOLD, 28));
        lblBrandTitle.setForeground(new Color(17, 24, 39));

        lblBrandSubtitle.setFont(new Font("Segoe UI", Font.BOLD, 18));
        lblBrandSubtitle.setForeground(new Color(5, 150, 105));

        lblBrandDesc1.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        lblBrandDesc1.setForeground(new Color(107, 114, 128));

        lblBrandDesc2.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        lblBrandDesc2.setForeground(new Color(107, 114, 128));

        lblLoginTitle.setFont(new Font("Segoe UI", Font.BOLD, 22));
        lblLoginTitle.setForeground(new Color(17, 24, 39));

        lblLoginSubtitle.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        lblLoginSubtitle.setForeground(new Color(107, 114, 128));

        styleInput(txtUsername);
        styleInput(txtPassword);
        styleLoginButton(btnLogin);
    }

    private void styleInput(JTextField textField) {
        textField.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        textField.setBackground(Color.WHITE);
        textField.setForeground(new Color(17, 24, 39));

        textField.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(229, 231, 235)),
                BorderFactory.createEmptyBorder(8, 12, 8, 12)
        ));

        textField.putClientProperty("JComponent.roundRect", true);
    }

    private void styleLoginButton(JButton button) {
        button.setBackground(new Color(5, 150, 105));
        button.setForeground(Color.WHITE);
        button.setFont(new Font("Segoe UI", Font.BOLD, 13));

        button.setFocusPainted(false);
        button.setBorderPainted(false);

        button.setBorder(BorderFactory.createEmptyBorder(10, 16, 10, 16));
        button.putClientProperty("JButton.buttonType", "roundRect");
    }

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        setupLoginUI();
        txtUsername.putClientProperty("JTextField.placeholderText", "Masukkan username");
        txtPassword.putClientProperty("JTextField.placeholderText", "Masukkan password");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        lblBrandSubtitle = new javax.swing.JLabel();
        lblBrandTitle = new javax.swing.JLabel();
        lblBrandDesc1 = new javax.swing.JLabel();
        lblBrandDesc2 = new javax.swing.JLabel();
        loginCardPanel = new javax.swing.JPanel();
        lblLoginTitle = new javax.swing.JLabel();
        lblLoginSubtitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - Smart Inventory Management");
        setMinimumSize(new java.awt.Dimension(900, 550));
        setPreferredSize(new java.awt.Dimension(900, 550));
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(243, 244, 246));
        mainPanel.setMinimumSize(new java.awt.Dimension(900, 550));

        leftPanel.setBackground(new java.awt.Color(243, 244, 246));
        leftPanel.setMinimumSize(new java.awt.Dimension(430, 450));
        leftPanel.setPreferredSize(new java.awt.Dimension(430, 450));

        lblBrandSubtitle.setBackground(new java.awt.Color(5, 150, 105));
        lblBrandSubtitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBrandSubtitle.setText("Gudang Digital");

        lblBrandTitle.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblBrandTitle.setText("Smart Inventory Management");

        lblBrandDesc1.setBackground(new java.awt.Color(107, 114, 128));
        lblBrandDesc1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBrandDesc1.setText("Sistem pengelolaan stok barang masuk,");

        lblBrandDesc2.setBackground(new java.awt.Color(107, 114, 128));
        lblBrandDesc2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBrandDesc2.setText("stok keluar, kategori, dan laporan gudang.");

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBrandDesc2)
                    .addComponent(lblBrandDesc1)
                    .addComponent(lblBrandSubtitle))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(leftPanelLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lblBrandTitle)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(lblBrandSubtitle)
                .addGap(18, 18, 18)
                .addComponent(lblBrandDesc1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBrandDesc2)
                .addContainerGap(227, Short.MAX_VALUE))
            .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(leftPanelLayout.createSequentialGroup()
                    .addGap(89, 89, 89)
                    .addComponent(lblBrandTitle)
                    .addContainerGap(323, Short.MAX_VALUE)))
        );

        loginCardPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginCardPanel.setMinimumSize(new java.awt.Dimension(330, 360));

        lblLoginTitle.setBackground(new java.awt.Color(17, 24, 39));
        lblLoginTitle.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblLoginTitle.setText("LOGIN");

        lblLoginSubtitle.setBackground(new java.awt.Color(107, 114, 128));
        lblLoginSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblLoginSubtitle.setText("Masuk ke akun Anda");

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblUsername.setText("Username");

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtUsername.setMinimumSize(new java.awt.Dimension(250, 36));
        txtUsername.setPreferredSize(new java.awt.Dimension(250, 36));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblPassword.setText("Password");

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setMinimumSize(new java.awt.Dimension(250, 40));
        btnLogin.setPreferredSize(new java.awt.Dimension(250, 40));
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtPassword.setMinimumSize(new java.awt.Dimension(250, 36));
        txtPassword.setPreferredSize(new java.awt.Dimension(250, 36));

        javax.swing.GroupLayout loginCardPanelLayout = new javax.swing.GroupLayout(loginCardPanel);
        loginCardPanel.setLayout(loginCardPanelLayout);
        loginCardPanelLayout.setHorizontalGroup(
            loginCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginCardPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(loginCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsername)
                    .addComponent(lblPassword)
                    .addComponent(lblLoginSubtitle)
                    .addComponent(lblLoginTitle)
                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        loginCardPanelLayout.setVerticalGroup(
            loginCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginCardPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblLoginTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoginSubtitle)
                .addGap(18, 18, 18)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(loginCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
            .addComponent(loginCardPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            String username = txtUsername.getText();
            String password = new String(txtPassword.getPassword());

            User user = authService.login(username, password);

            JOptionPane.showMessageDialog(
                    this,
                    "Login berhasil sebagai " + user.getRole()
            );

            MainFrame mainFrame = new MainFrame(user);
            mainFrame.setVisible(true);

            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage()
            );
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblBrandDesc1;
    private javax.swing.JLabel lblBrandDesc2;
    private javax.swing.JLabel lblBrandSubtitle;
    private javax.swing.JLabel lblBrandTitle;
    private javax.swing.JLabel lblLoginSubtitle;
    private javax.swing.JLabel lblLoginTitle;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel loginCardPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
